In [30]:
# ## NUMPY
# ## NumPy (Numerical Python) is a powerful Python library used for numerical computing.
# It provides:

# Support for large, multi-dimensional arrays and matrices.
# Mathematical functions to operate on these arrays efficiently.
# Tools for performing operations like linear algebra, statistics, 
# and random number generation.
# NumPy is widely used in data science, machine learning, 
# and scientific computing because it is fast and easy to use for handling numerical data.

In [58]:
!pip install numpy

In [31]:
## CREATE ARRAY USING NUMPY
## cREATE A 1D ARRAY
import numpy as np

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)




[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [32]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape([1,5])

array([[1, 2, 3, 4, 5]])

In [33]:
arr2 =np.array([[1,2,3,4,5]])
arr2.shape

(1, 5)

In [34]:
arr2 =np.array([[1,2,3,4,5],[2,3,4,5,6]])
print (arr2)
print( arr2.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [35]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [36]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [37]:
#IDENTITY MATRIX
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:\n", arr)
print("Shape:", arr.shape) # Output: (2, 3)
print("Number of dimensions:", arr.ndim) # Output: 2
print("Size (number of elements):", arr.size) # Output: 6
print("Data type:", arr.dtype) # Output: int64 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize) # Output: 8 (may vary based on platform)
print("Item size (in bytes):", arr.itemsize) # Output: 8 (may vary based on platform)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8
Item size (in bytes): 8


In [39]:
### Numpy Vectorized Operation
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

### Element Wise addition
print("Addition:", arr1 + arr2)

## Element Wise Substraction
print("Substraction:", arr1 - arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)

## Element-wise division
print("Division:", arr1 / arr2)

Addition: [11 22 33 44 55]
Substraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [40]:
## Universal Function
arr = np.array([2, 3, 4, 5, 6])

## square root
print(np.sqrt(arr))

## Exponential
print(np.exp(arr))

## Sine
print(np.sin(arr))

## natural log
print(np.log(arr))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [41]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Array:\n", arr)

Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [42]:
arr[0][0]

np.int64(1)

In [43]:
arr[2:]
arr[1:]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [44]:
print (arr[0:4])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [45]:
print (arr[1:,2:])

[[ 7  8]
 [11 12]]


In [47]:
print(arr[1:, 1:3])

[[ 6  7]
 [10 11]]


In [49]:
## Modify array elements
arr[0,0]= 100
print(arr)

[[100   2   3   4]
 [  5   6   7   8]
 [  9  10  11  12]]


In [50]:
arr[1:]= 100
print(arr)

[[100   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [51]:
### statistical concepts--Normalization
# to have a mean of 0 and standard deviation of 1

data = np.array([1, 2, 3, 4, 5])

# Calculate the mean and standard deviation
mean = np.mean(data)
std_dev = np.std(data)

# Normalize the data
normalized_data = (data - mean) / std_dev
print("Normalized data:", normalized_data)

# Output:
# Normalized data: [-1.26491106 -0.63245553  0.  0.63245553  1.26491106]

Normalized data: [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [52]:
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Mean
mean = np.mean(data)
print("Mean:", mean)

# Median
median = np.median(data)
print("Median:", median)

# Standard deviation
std_dev = np.std(data)
print("Standard Deviation:", std_dev)

# Variance
variance = np.var(data)
print("Variance:", variance)

Mean: 5.5
Median: 5.5
Standard Deviation: 2.8722813232690143
Variance: 8.25


In [ ]:
#LOGICAL OPERATOR
data= np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5) & (data<=8)]     ## and operator

array([5, 6, 7, 8])

In [ ]:
data= np.array([1,2,3,4,5,6,7,8,9,10])
data[(data>=5) | (data<=8)]     ##or operator

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])